#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ICE_Bind.Resource", IsApplication=true)]

namespace ICE_Bind
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			// aapt resource value: 0x7f01002a
			public const int mv_backgroundColor = 2130772010;
			
			// aapt resource value: 0x7f01002b
			public const int mv_cornerRadius = 2130772011;
			
			// aapt resource value: 0x7f01002e
			public const int mv_isRadiusHalfHeight = 2130772014;
			
			// aapt resource value: 0x7f01002f
			public const int mv_isWidthHeightEqual = 2130772015;
			
			// aapt resource value: 0x7f01002d
			public const int mv_strokeColor = 2130772013;
			
			// aapt resource value: 0x7f01002c
			public const int mv_strokeWidth = 2130772012;
			
			// aapt resource value: 0x7f010030
			public const int tl_bar_color = 2130772016;
			
			// aapt resource value: 0x7f010031
			public const int tl_bar_stroke_color = 2130772017;
			
			// aapt resource value: 0x7f010032
			public const int tl_bar_stroke_width = 2130772018;
			
			// aapt resource value: 0x7f010009
			public const int tl_divider_color = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int tl_divider_padding = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int tl_divider_width = 2130771979;
			
			// aapt resource value: 0x7f010028
			public const int tl_iconGravity = 2130772008;
			
			// aapt resource value: 0x7f010026
			public const int tl_iconHeight = 2130772006;
			
			// aapt resource value: 0x7f010029
			public const int tl_iconMargin = 2130772009;
			
			// aapt resource value: 0x7f010027
			public const int tl_iconVisible = 2130772007;
			
			// aapt resource value: 0x7f010025
			public const int tl_iconWidth = 2130772005;
			
			// aapt resource value: 0x7f01000c
			public const int tl_indicator_anim_duration = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int tl_indicator_anim_enable = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int tl_indicator_bounce_enable = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int tl_indicator_color = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int tl_indicator_corner_radius = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int tl_indicator_gravity = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int tl_indicator_height = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int tl_indicator_margin_bottom = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int tl_indicator_margin_left = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int tl_indicator_margin_right = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int tl_indicator_margin_top = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int tl_indicator_style = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int tl_indicator_width = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int tl_indicator_width_equal_title = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int tl_tab_padding = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int tl_tab_space_equal = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int tl_tab_width = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int tl_textAllCaps = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int tl_textBold = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int tl_textSelectColor = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int tl_textUnselectColor = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int tl_textsize = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int tl_underline_color = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int tl_underline_gravity = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int tl_underline_height = 2130772004;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public const int abc_action_bar_embed_tabs = 2131230720;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int notification_action_color_filter = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int notification_icon_bg_color = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int notification_material_background_media_default_color = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int primary_text_default_material_dark = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int ripple_material_light = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int secondary_text_default_material_dark = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int secondary_text_default_material_light = 2131034118;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090004
			public const int compat_button_inset_horizontal_material = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int compat_button_inset_vertical_material = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int compat_button_padding_horizontal_material = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int compat_button_padding_vertical_material = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int compat_control_corner_material = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int notification_action_icon_size = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int notification_action_text_size = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int notification_big_circle_margin = 2131296267;
			
			// aapt resource value: 0x7f090001
			public const int notification_content_margin_start = 2131296257;
			
			// aapt resource value: 0x7f09000c
			public const int notification_large_icon_height = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int notification_large_icon_width = 2131296269;
			
			// aapt resource value: 0x7f090002
			public const int notification_main_column_padding_top = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int notification_media_narrow_margin = 2131296259;
			
			// aapt resource value: 0x7f09000e
			public const int notification_right_icon_size = 2131296270;
			
			// aapt resource value: 0x7f090000
			public const int notification_right_side_padding_top = 2131296256;
			
			// aapt resource value: 0x7f09000f
			public const int notification_small_icon_background_padding = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int notification_small_icon_size_as_large = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int notification_subtext_size = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int notification_top_pad = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int notification_top_pad_large_text = 2131296275;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f02000a
			public const int notification_template_icon_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_low_bg = 2130837515;
			
			// aapt resource value: 0x7f020008
			public const int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notify_panel_notification_icon_bg = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000d
			public const int BLOCK = 2131361805;
			
			// aapt resource value: 0x7f0a0010
			public const int BOTH = 2131361808;
			
			// aapt resource value: 0x7f0a000b
			public const int BOTTOM = 2131361803;
			
			// aapt resource value: 0x7f0a0013
			public const int LEFT = 2131361811;
			
			// aapt resource value: 0x7f0a0011
			public const int NONE = 2131361809;
			
			// aapt resource value: 0x7f0a000e
			public const int NORMAL = 2131361806;
			
			// aapt resource value: 0x7f0a0014
			public const int RIGHT = 2131361812;
			
			// aapt resource value: 0x7f0a0012
			public const int SELECT = 2131361810;
			
			// aapt resource value: 0x7f0a000c
			public const int TOP = 2131361804;
			
			// aapt resource value: 0x7f0a000f
			public const int TRIANGLE = 2131361807;
			
			// aapt resource value: 0x7f0a001e
			public const int action0 = 2131361822;
			
			// aapt resource value: 0x7f0a001b
			public const int action_container = 2131361819;
			
			// aapt resource value: 0x7f0a0022
			public const int action_divider = 2131361826;
			
			// aapt resource value: 0x7f0a001c
			public const int action_image = 2131361820;
			
			// aapt resource value: 0x7f0a001d
			public const int action_text = 2131361821;
			
			// aapt resource value: 0x7f0a002c
			public const int actions = 2131361836;
			
			// aapt resource value: 0x7f0a0006
			public const int async = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int blocking = 2131361799;
			
			// aapt resource value: 0x7f0a001f
			public const int cancel_action = 2131361823;
			
			// aapt resource value: 0x7f0a0027
			public const int chronometer = 2131361831;
			
			// aapt resource value: 0x7f0a002e
			public const int end_padder = 2131361838;
			
			// aapt resource value: 0x7f0a0008
			public const int forever = 2131361800;
			
			// aapt resource value: 0x7f0a0029
			public const int icon = 2131361833;
			
			// aapt resource value: 0x7f0a002d
			public const int icon_group = 2131361837;
			
			// aapt resource value: 0x7f0a0028
			public const int info = 2131361832;
			
			// aapt resource value: 0x7f0a0009
			public const int italic = 2131361801;
			
			// aapt resource value: 0x7f0a0018
			public const int iv_tab_icon = 2131361816;
			
			// aapt resource value: 0x7f0a0000
			public const int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a0017
			public const int ll_tap = 2131361815;
			
			// aapt resource value: 0x7f0a0021
			public const int media_actions = 2131361825;
			
			// aapt resource value: 0x7f0a000a
			public const int normal = 2131361802;
			
			// aapt resource value: 0x7f0a002b
			public const int notification_background = 2131361835;
			
			// aapt resource value: 0x7f0a0024
			public const int notification_main_column = 2131361828;
			
			// aapt resource value: 0x7f0a0023
			public const int notification_main_column_container = 2131361827;
			
			// aapt resource value: 0x7f0a002a
			public const int right_icon = 2131361834;
			
			// aapt resource value: 0x7f0a0025
			public const int right_side = 2131361829;
			
			// aapt resource value: 0x7f0a0016
			public const int rtv_msg_tip = 2131361814;
			
			// aapt resource value: 0x7f0a0020
			public const int status_bar_latest_event_content = 2131361824;
			
			// aapt resource value: 0x7f0a0002
			public const int tag_transition_group = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int text = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int text2 = 2131361796;
			
			// aapt resource value: 0x7f0a0026
			public const int time = 2131361830;
			
			// aapt resource value: 0x7f0a0005
			public const int title = 2131361797;
			
			// aapt resource value: 0x7f0a0019
			public const int tl_1 = 2131361817;
			
			// aapt resource value: 0x7f0a0015
			public const int tv_tab_title = 2131361813;
			
			// aapt resource value: 0x7f0a001a
			public const int vp = 2131361818;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int cancel_button_image_alpha = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int status_bar_notification_info_maxnum = 2131099649;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layout_tab = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int layout_tab_bottom = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int layout_tab_left = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int layout_tab_right = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int layout_tab_segment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int layout_tab_top = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_action = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_action_tombstone = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_media_action = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_media_cancel_action = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_big_media = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_big_media_custom = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_big_media_narrow = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_big_media_narrow_custom = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_custom_big = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_template_icon_group = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int notification_template_lines_media = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int notification_template_media = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int notification_template_media_custom = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int notification_template_part_chronometer = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int notification_template_part_time = 2130903061;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int status_bar_notification_info_overflow = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040005
			public const int TextAppearance_Compat_Notification = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int TextAppearance_Compat_Notification_Info = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int TextAppearance_Compat_Notification_Info_Media = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int TextAppearance_Compat_Notification_Line2 = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int TextAppearance_Compat_Notification_Media = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int TextAppearance_Compat_Notification_Time = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int TextAppearance_Compat_Notification_Time_Media = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int TextAppearance_Compat_Notification_Title = 2130968584;
			
			// aapt resource value: 0x7f040003
			public const int TextAppearance_Compat_Notification_Title_Media = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int Widget_Compat_NotificationActionContainer = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Widget_Compat_NotificationActionText = 2130968586;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CommonTabLayout = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009};
			
			// aapt resource value: 0
			public const int CommonTabLayout_tl_divider_color = 0;
			
			// aapt resource value: 1
			public const int CommonTabLayout_tl_divider_padding = 1;
			
			// aapt resource value: 2
			public const int CommonTabLayout_tl_divider_width = 2;
			
			// aapt resource value: 30
			public const int CommonTabLayout_tl_iconGravity = 30;
			
			// aapt resource value: 28
			public const int CommonTabLayout_tl_iconHeight = 28;
			
			// aapt resource value: 31
			public const int CommonTabLayout_tl_iconMargin = 31;
			
			// aapt resource value: 29
			public const int CommonTabLayout_tl_iconVisible = 29;
			
			// aapt resource value: 27
			public const int CommonTabLayout_tl_iconWidth = 27;
			
			// aapt resource value: 3
			public const int CommonTabLayout_tl_indicator_anim_duration = 3;
			
			// aapt resource value: 4
			public const int CommonTabLayout_tl_indicator_anim_enable = 4;
			
			// aapt resource value: 5
			public const int CommonTabLayout_tl_indicator_bounce_enable = 5;
			
			// aapt resource value: 6
			public const int CommonTabLayout_tl_indicator_color = 6;
			
			// aapt resource value: 7
			public const int CommonTabLayout_tl_indicator_corner_radius = 7;
			
			// aapt resource value: 8
			public const int CommonTabLayout_tl_indicator_gravity = 8;
			
			// aapt resource value: 9
			public const int CommonTabLayout_tl_indicator_height = 9;
			
			// aapt resource value: 10
			public const int CommonTabLayout_tl_indicator_margin_bottom = 10;
			
			// aapt resource value: 11
			public const int CommonTabLayout_tl_indicator_margin_left = 11;
			
			// aapt resource value: 12
			public const int CommonTabLayout_tl_indicator_margin_right = 12;
			
			// aapt resource value: 13
			public const int CommonTabLayout_tl_indicator_margin_top = 13;
			
			// aapt resource value: 14
			public const int CommonTabLayout_tl_indicator_style = 14;
			
			// aapt resource value: 15
			public const int CommonTabLayout_tl_indicator_width = 15;
			
			// aapt resource value: 16
			public const int CommonTabLayout_tl_tab_padding = 16;
			
			// aapt resource value: 17
			public const int CommonTabLayout_tl_tab_space_equal = 17;
			
			// aapt resource value: 18
			public const int CommonTabLayout_tl_tab_width = 18;
			
			// aapt resource value: 19
			public const int CommonTabLayout_tl_textAllCaps = 19;
			
			// aapt resource value: 20
			public const int CommonTabLayout_tl_textBold = 20;
			
			// aapt resource value: 21
			public const int CommonTabLayout_tl_textSelectColor = 21;
			
			// aapt resource value: 22
			public const int CommonTabLayout_tl_textUnselectColor = 22;
			
			// aapt resource value: 23
			public const int CommonTabLayout_tl_textsize = 23;
			
			// aapt resource value: 24
			public const int CommonTabLayout_tl_underline_color = 24;
			
			// aapt resource value: 25
			public const int CommonTabLayout_tl_underline_gravity = 25;
			
			// aapt resource value: 26
			public const int CommonTabLayout_tl_underline_height = 26;
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			public static int[] MsgView = new int[] {
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015};
			
			// aapt resource value: 0
			public const int MsgView_mv_backgroundColor = 0;
			
			// aapt resource value: 1
			public const int MsgView_mv_cornerRadius = 1;
			
			// aapt resource value: 4
			public const int MsgView_mv_isRadiusHalfHeight = 4;
			
			// aapt resource value: 5
			public const int MsgView_mv_isWidthHeightEqual = 5;
			
			// aapt resource value: 3
			public const int MsgView_mv_strokeColor = 3;
			
			// aapt resource value: 2
			public const int MsgView_mv_strokeWidth = 2;
			
			public static int[] SegmentTabLayout = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772016,
					2130772017,
					2130772018};
			
			// aapt resource value: 21
			public const int SegmentTabLayout_tl_bar_color = 21;
			
			// aapt resource value: 22
			public const int SegmentTabLayout_tl_bar_stroke_color = 22;
			
			// aapt resource value: 23
			public const int SegmentTabLayout_tl_bar_stroke_width = 23;
			
			// aapt resource value: 0
			public const int SegmentTabLayout_tl_divider_color = 0;
			
			// aapt resource value: 1
			public const int SegmentTabLayout_tl_divider_padding = 1;
			
			// aapt resource value: 2
			public const int SegmentTabLayout_tl_divider_width = 2;
			
			// aapt resource value: 3
			public const int SegmentTabLayout_tl_indicator_anim_duration = 3;
			
			// aapt resource value: 4
			public const int SegmentTabLayout_tl_indicator_anim_enable = 4;
			
			// aapt resource value: 5
			public const int SegmentTabLayout_tl_indicator_bounce_enable = 5;
			
			// aapt resource value: 6
			public const int SegmentTabLayout_tl_indicator_color = 6;
			
			// aapt resource value: 7
			public const int SegmentTabLayout_tl_indicator_corner_radius = 7;
			
			// aapt resource value: 8
			public const int SegmentTabLayout_tl_indicator_height = 8;
			
			// aapt resource value: 9
			public const int SegmentTabLayout_tl_indicator_margin_bottom = 9;
			
			// aapt resource value: 10
			public const int SegmentTabLayout_tl_indicator_margin_left = 10;
			
			// aapt resource value: 11
			public const int SegmentTabLayout_tl_indicator_margin_right = 11;
			
			// aapt resource value: 12
			public const int SegmentTabLayout_tl_indicator_margin_top = 12;
			
			// aapt resource value: 13
			public const int SegmentTabLayout_tl_tab_padding = 13;
			
			// aapt resource value: 14
			public const int SegmentTabLayout_tl_tab_space_equal = 14;
			
			// aapt resource value: 15
			public const int SegmentTabLayout_tl_tab_width = 15;
			
			// aapt resource value: 16
			public const int SegmentTabLayout_tl_textAllCaps = 16;
			
			// aapt resource value: 17
			public const int SegmentTabLayout_tl_textBold = 17;
			
			// aapt resource value: 18
			public const int SegmentTabLayout_tl_textSelectColor = 18;
			
			// aapt resource value: 19
			public const int SegmentTabLayout_tl_textUnselectColor = 19;
			
			// aapt resource value: 20
			public const int SegmentTabLayout_tl_textsize = 20;
			
			public static int[] SlidingTabLayout = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004};
			
			// aapt resource value: 0
			public const int SlidingTabLayout_tl_divider_color = 0;
			
			// aapt resource value: 1
			public const int SlidingTabLayout_tl_divider_padding = 1;
			
			// aapt resource value: 2
			public const int SlidingTabLayout_tl_divider_width = 2;
			
			// aapt resource value: 3
			public const int SlidingTabLayout_tl_indicator_color = 3;
			
			// aapt resource value: 4
			public const int SlidingTabLayout_tl_indicator_corner_radius = 4;
			
			// aapt resource value: 5
			public const int SlidingTabLayout_tl_indicator_gravity = 5;
			
			// aapt resource value: 6
			public const int SlidingTabLayout_tl_indicator_height = 6;
			
			// aapt resource value: 7
			public const int SlidingTabLayout_tl_indicator_margin_bottom = 7;
			
			// aapt resource value: 8
			public const int SlidingTabLayout_tl_indicator_margin_left = 8;
			
			// aapt resource value: 9
			public const int SlidingTabLayout_tl_indicator_margin_right = 9;
			
			// aapt resource value: 10
			public const int SlidingTabLayout_tl_indicator_margin_top = 10;
			
			// aapt resource value: 11
			public const int SlidingTabLayout_tl_indicator_style = 11;
			
			// aapt resource value: 12
			public const int SlidingTabLayout_tl_indicator_width = 12;
			
			// aapt resource value: 13
			public const int SlidingTabLayout_tl_indicator_width_equal_title = 13;
			
			// aapt resource value: 14
			public const int SlidingTabLayout_tl_tab_padding = 14;
			
			// aapt resource value: 15
			public const int SlidingTabLayout_tl_tab_space_equal = 15;
			
			// aapt resource value: 16
			public const int SlidingTabLayout_tl_tab_width = 16;
			
			// aapt resource value: 17
			public const int SlidingTabLayout_tl_textAllCaps = 17;
			
			// aapt resource value: 18
			public const int SlidingTabLayout_tl_textBold = 18;
			
			// aapt resource value: 19
			public const int SlidingTabLayout_tl_textSelectColor = 19;
			
			// aapt resource value: 20
			public const int SlidingTabLayout_tl_textUnselectColor = 20;
			
			// aapt resource value: 21
			public const int SlidingTabLayout_tl_textsize = 21;
			
			// aapt resource value: 22
			public const int SlidingTabLayout_tl_underline_color = 22;
			
			// aapt resource value: 23
			public const int SlidingTabLayout_tl_underline_gravity = 23;
			
			// aapt resource value: 24
			public const int SlidingTabLayout_tl_underline_height = 24;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
